name: restro
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  firebase_messaging: ^16.0.4
  firebase_storage: ^13.0.4
  sqflite: ^2.4.1
  path: ^1.9.0
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  image_picker: ^1.1.2
  shimmer: ^3.0.0
  intl: ^0.20.2
  uuid: ^4.2.1
  flutter_local_notifications: ^17.2.3
  timezone: ^0.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.jpg"

flutter:
  uses-material-design: true

  assets:
    - assets/images/